[GLOBAL]
pants_version = "2.20.1"
backend_packages.add = [
  "pants.backend.awslambda.python",
  "pants.backend.python",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.black"
]

[python]
interpreter_constraints = ["==3.10.*"]


[pytest]
args = ["-s"]

[flake8]
args = ["--max-line-length 88", "--ignore=E501,W503"]

[coverage-py]
report = ["console","json","html"]
